### Importing Libraries :-

In [1]:
import pandas as pd
import numpy as np

In [8]:
cust.shape

(15266, 10)

In [9]:
sales.shape

(62884, 10)

In [10]:
product.shape

(2517, 10)

In [11]:
Stores.shape

(67, 5)

In [16]:
sales['Order Number'].unique

KeyError: 'Order Number'

### LOADING THE DATASET:-

#### Customers Data :-

In [3]:
cust = pd.read_csv(r"C:\Users\Rohit kumar\Downloads\Customers.csv",encoding='utf-8', encoding_errors='replace')
cust.head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,07-03-1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

#### Sales Data :-

In [4]:
sales = pd.read_csv(r"C:\Users\Rohit kumar\Downloads\Sales.csv")
sales.head()

,OrderNumber,LineItem,OrderDate,DeliveryDate,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,StoreMode
0,366000,1,01-01-2016,NaN,265598,10,1304,1,CAD,Offline Store
1,366001,1,01-01-2016,13-01-2016,1269051,0,1048,2,USD,Online Mode
2,366001,2,01-01-2016,13-01-2016,1269051,0,2007,1,USD,Online Mode
3,366002,1,01-01-2016,12-01-2016,266019,0,1106,7,CAD,Online Mode
4,366002,2,01-01-2016,12-01-2016,266019,0,373,1,CAD,Online Mode

#### Product Data :-

In [5]:
product = pd.read_csv(r"C:\Users\Rohit kumar\Downloads\Products.csv")
product.head()

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

#### Exchange Rate Data :-

In [6]:
Exchange = pd.read_csv(r"C:\Users\Rohit kumar\Downloads\Exchange_Rates.csv")
Exchange.head()

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415

#### Stores Data :-

In [7]:
Stores = pd.read_csv(r"C:\Users\Rohit kumar\Downloads\Stores.csv")
Stores.head()

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

### 1). EDA on Customers Table:-

In [51]:
cust.shape

(15266, 10)

In [52]:
cust.head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,07-03-1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [53]:
cust.sample(5)

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
10650,1489650,Male,Albert Merritt,Fairport,NY,New York,14450,United States,North America,11-06-1988
148,21523,Male,Jayden Rennie,SWANHAVEN,NSW,New South Wales,2540,Australia,Australia,12-06-1969
8921,1263974,Female,Elizabeth Billy,Fort Walton Beach,FL,Florida,32547,United States,North America,09-06-1970
9517,1344122,Female,Jessica Jenkins,Archer,FL,Florida,32618,United States,North America,12/27/1989
7644,1081249,Female,Laura Kirby,ACHNACLYTH,Highland,Highland,KW6 2LN,United Kingdom,Europe,1/24/1967

In [54]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15256 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.2+ MB

In [55]:
cust.isnull().sum()

CustomerKey     0
Gender          0
Name            0
City            0
State Code     10
State           0
Zip Code        0
Country         0
Continent       0
Birthday        0
dtype: int64

In [56]:

# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_colwidth', None)
# pd.set_option('display.max_rows', None)

In [57]:
# cust.groupby('State')['State Code'].unique()

#### 🧐Check In which rows we have nan value :-

In [58]:

cust[cust.isnull().any(axis=1)]

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
5304,729681,Female,Rossana Padovesi,Polvica,NaN,Napoli,80035,Italy,Europe,4/18/1981
5316,732289,Male,Indro Piccio,Varcaturo,NaN,Napoli,80014,Italy,Europe,2/24/1949
5372,742042,Male,Amaranto Loggia,Casaferro,NaN,Napoli,80034,Italy,Europe,3/14/1936
5377,742886,Female,Edmonda Capon,Terzigno,NaN,Napoli,80040,Italy,Europe,08-06-1963
5378,743343,Female,Ambra Sagese,Pomigliano D'Arco,NaN,Napoli,80038,Italy,Europe,01-05-1961
5485,759705,Male,Callisto Lo Duca,Casilli,NaN,Napoli,80047,Italy,Europe,8/28/1976
5525,765589,Male,Michelino Lucchesi,Pompei Scavi,NaN,Napoli,80045,Italy,Europe,11/13/1947
5531,766410,Male,Adelmio Beneventi,Licola,NaN,Napoli,80078,Italy,Europe,1/13/1940
5631,781667,Female,Ilda Manna,Napoli,NaN,Napoli,80134,Italy,Europe,05-08-1977
5695,789177,Male,Calogero Folliero,Mariglianella,NaN,Napoli,80030,Italy,Europe,03-03-2000

##### 👉 Only Napoli state code is missing so i replace it with NL because only one state cose is missing

#### 🛠️ Fix the NaN in the State Code:-

In [59]:
cust['State Code'] = cust['State Code'].fillna('NL')

In [60]:
# Check the nan value 
cust.isnull().sum()

CustomerKey    0
Gender         0
Name           0
City           0
State Code     0
State          0
Zip Code       0
Country        0
Continent      0
Birthday       0
dtype: int64

In [61]:
####✔️ Check the Napoli column
cust[cust['State'] == 'Napoli']

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
5304,729681,Female,Rossana Padovesi,Polvica,NL,Napoli,80035,Italy,Europe,4/18/1981
5316,732289,Male,Indro Piccio,Varcaturo,NL,Napoli,80014,Italy,Europe,2/24/1949
5372,742042,Male,Amaranto Loggia,Casaferro,NL,Napoli,80034,Italy,Europe,3/14/1936
5377,742886,Female,Edmonda Capon,Terzigno,NL,Napoli,80040,Italy,Europe,08-06-1963
5378,743343,Female,Ambra Sagese,Pomigliano D'Arco,NL,Napoli,80038,Italy,Europe,01-05-1961
5485,759705,Male,Callisto Lo Duca,Casilli,NL,Napoli,80047,Italy,Europe,8/28/1976
5525,765589,Male,Michelino Lucchesi,Pompei Scavi,NL,Napoli,80045,Italy,Europe,11/13/1947
5531,766410,Male,Adelmio Beneventi,Licola,NL,Napoli,80078,Italy,Europe,1/13/1940
5631,781667,Female,Ilda Manna,Napoli,NL,Napoli,80134,Italy,Europe,05-08-1977
5695,789177,Male,Calogero Folliero,Mariglianella,NL,Napoli,80030,Italy,Europe,03-03-2000

In [62]:
cust.columns

Index(['CustomerKey', 'Gender', 'Name', 'City', 'State Code', 'State',
       'Zip Code', 'Country', 'Continent', 'Birthday'],
      dtype='object')

### Remove Incosistency in names columns:-

##### 🧹 Removes � from the Name column

In [63]:
# Check the

In [81]:
cust['Name'] = cust['Name'].str.replace('�',"")
cust['City'] = cust['City'].str.replace('�',"")
cust['State'] = cust['State'].str.replace('�',"")

In [82]:
cust[cust['CustomerKey'] == 2099600]

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
15261,2099600,Female,Denisa Dukov,Houston,TX,Texas,77017,United States,North America,3-25-1936

In [83]:
cust[cust['CustomerKey'] == 454932]

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
3393,454932,Female,Christin Fuerst,Mnchen,BY,Freistaat Bayern,80741,Germany,Europe,3-13-1985

#### Fix country and continent

In [84]:
cust.groupby('Country')['Continent'].unique()

Country
Australia               [Oceania]
Canada            [North America]
France                   [Europe]
Germany                  [Europe]
Italy                    [Europe]
Netherlands              [Europe]
United Kingdom           [Europe]
United States     [North America]
Name: Continent, dtype: object

In [85]:
cust['Country'].unique().tolist()

['Australia',
 'Canada',
 'Germany',
 'France',
 'Italy',
 'Netherlands',
 'United Kingdom',
 'United States']

#### Fix the Australia columns its continent should be Oceania :-

In [86]:
cust[cust['Country']== 'Australia'].head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Oceania,07-03-1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Oceania,9-27-1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Oceania,5-26-1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Oceania,9-17-1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Oceania,11-19-1965

In [87]:
cust.loc[cust['Country']== 'Australia','Continent'] = 'Oceania'

In [88]:
# Fix the Australia Ocean :-
cust[cust['Country']== 'Australia'].head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Oceania,07-03-1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Oceania,9-27-1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Oceania,5-26-1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Oceania,9-17-1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Oceania,11-19-1965

#### 🛠️ Fix the  data types of all columns:-

In [89]:
# Check the data types:-
cust.dtypes

CustomerKey     int64
Gender         object
Name           object
City           object
State Code     object
State          object
Zip Code       object
Country        object
Continent      object
Birthday       object
dtype: object

##### 👉 There is one columns in which data types is wrong :- 
  ###### 1)-Birthday

##### 1) Birthday :-

In [90]:
cust['Birthday'].dtypes

dtype('O')

In [91]:
cust['Birthday'].unique()

array(['07-03-1939', '9-27-1979', '5-26-1947', ..., '3-25-1936',
       '11-09-1937', '8-18-1965'], dtype=object)

In [92]:
## Chnage the date column into date dtypes 
# cust['Birthday'] = pd.to_datetime(cust['Birthday'],errors = 'coerce')

In [93]:
cust['Birthday'] = cust['Birthday'].str.replace("/","-")

In [94]:
cust[cust['CustomerKey']== 1568]

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
9,1568,Male,Luke Virtue,KOTTA,VIC,Victoria,3565,Australia,Oceania,7-25-1975

In [95]:
cust[cust['CustomerKey']== 1314]

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
8,1314,Male,Isaac Israel,EDITH RIVER,NT,Northern Territory,852,Australia,Oceania,12-21-1965

In [96]:
cust['Birthday'].unique()

array(['07-03-1939', '9-27-1979', '5-26-1947', ..., '3-25-1936',
       '11-09-1937', '8-18-1965'], dtype=object)

In [97]:
cust.sample(10)

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
11673,1624311,Male,Eugene Morales,Indianapolis,IN,Indiana,46254,United States,North America,01-01-1960
4613,624293,Female,Fanchon Bourassa,SAINT-PRIEST,RA,Rhne-Alpes,69800,France,Europe,8-23-1984
2876,387530,Male,Kevin Houser,Orillia,ON,Ontario,L3V 1T4,Canada,North America,09-02-1977
5293,728022,Female,Jolanda Milani,Castellazzo,RE,Reggio Emilia,42048,Italy,Europe,5-19-1970
12708,1756921,Female,Sarah Luckett,Spokane,WA,Washington,99205,United States,North America,8-28-1952
8751,1242050,Female,Marketta Thompson,Southfield,MI,Michigan,48076,United States,North America,5-16-2000
12133,1686814,Male,George Shirley,Lexington,KY,Kentucky,40505,United States,North America,9-28-1984
590,85220,Male,Levi Prenzel,KOOJAN,WA,Western Australia,6510,Australia,Oceania,4-15-1984
1638,227416,Male,Michael Hicks,Red Deer,AB,Alberta,T4N 2A6,Canada,North America,7-23-2000
12430,1722247,Male,James Sosa,Tremont,PA,Pennsylvania,17981,United States,North America,04-09-1952

In [98]:
cust['Birthday'].unique()

array(['07-03-1939', '9-27-1979', '5-26-1947', ..., '3-25-1936',
       '11-09-1937', '8-18-1965'], dtype=object)

In [99]:
cust['Birthday'].dtypes

dtype('O')

In [100]:
cust['Birthday'] = pd.to_datetime(cust['Birthday'])

In [101]:
cust['Birthday'].dtypes

dtype('<M8[ns]')

In [102]:
cust.dtypes

CustomerKey             int64
Gender                 object
Name                   object
City                   object
State Code             object
State                  object
Zip Code               object
Country                object
Continent              object
Birthday       datetime64[ns]
dtype: object

In [103]:
## Check the date columns:-
cust['Birthday'].head()

0   1939-07-03
1   1979-09-27
2   1947-05-26
3   1957-09-17
4   1965-11-19
Name: Birthday, dtype: datetime64[ns]

In [104]:
cust['Birthday'].unique()

<DatetimeArray>
['1939-07-03 00:00:00', '1979-09-27 00:00:00', '1947-05-26 00:00:00',
 '1957-09-17 00:00:00', '1965-11-19 00:00:00', '1954-01-20 00:00:00',
 '1969-11-22 00:00:00', '1950-03-12 00:00:00', '1965-12-21 00:00:00',
 '1975-07-25 00:00:00',
 ...
 '1951-10-31 00:00:00', '1937-10-09 00:00:00', '2002-02-18 00:00:00',
 '1939-12-13 00:00:00', '1987-11-02 00:00:00', '1971-12-02 00:00:00',
 '2001-01-27 00:00:00', '1936-03-25 00:00:00', '1937-11-09 00:00:00',
 '1965-08-18 00:00:00']
Length: 11270, dtype: datetime64[ns]

In [105]:
cust[cust['CustomerKey']== 1568]

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
9,1568,Male,Luke Virtue,KOTTA,VIC,Victoria,3565,Australia,Oceania,1975-07-25

In [106]:
cust.head(10)

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Oceania,1939-07-03
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Oceania,1979-09-27
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Oceania,1947-05-26
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Oceania,1957-09-17
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Oceania,1965-11-19
5,1086,Male,Hayden Clegg,TEMPLERS,SA,South Australia,5371,Australia,Oceania,1954-01-20
6,1133,Male,Nicholas Caffyn,JUBILEE POCKET,QLD,Queensland,4802,Australia,Oceania,1969-11-22
7,1256,Male,Lincoln Jenks,KULLOGUM,QLD,Queensland,4660,Australia,Oceania,1950-03-12
8,1314,Male,Isaac Israel,EDITH RIVER,NT,Northern Territory,852,Australia,Oceania,1965-12-21
9,1568,Male,Luke Virtue,KOTTA,VIC,Victoria,3565,Australia,Oceania,1975-07-25

In [107]:
cust.dtypes

CustomerKey             int64
Gender                 object
Name                   object
City                   object
State Code             object
State                  object
Zip Code               object
Country                object
Continent              object
Birthday       datetime64[ns]
dtype: object

In [108]:
cust.head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Oceania,1939-07-03
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Oceania,1979-09-27
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Oceania,1947-05-26
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Oceania,1957-09-17
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Oceania,1965-11-19

In [109]:
cust.to_csv(r'C:\Users\Rohit kumar\Downloads\customer.csv')

In [ ]:
# 1086	Male	Hayden Clegg	TEMPLERS	SA	South Australia	5371	Australia	Australia	NaT
# 6	1133	Male	Nicholas Caffyn	JUBILEE POCKET	QLD	Queensland	4802	Australia	Australia	NaT
# 7	1256	Male	Lincoln Jenks	KULLOGUM	QLD	Queensland	4660	Australia	Australia	NaT
# 8	1314	Male	Isaac Israel	EDITH RIVER	NT	Northern Territory	852	Australia	Australia	NaT
# 9	1568

In [230]:
# cust[cust['Birthday'].isnull().any(axis = 0)]
cust.isnull().sum()

CustomerKey     0
Gender          0
Name            0
City            0
State Code     10
State           0
Zip Code        0
Country         0
Continent       0
Birthday        0
dtype: int64

### 2). EDA on Sales Table:-

In [17]:
sales.head()

,OrderNumber,LineItem,OrderDate,DeliveryDate,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,StoreMode
0,366000,1,01-01-2016,NaN,265598,10,1304,1,CAD,Offline Store
1,366001,1,01-01-2016,13-01-2016,1269051,0,1048,2,USD,Online Mode
2,366001,2,01-01-2016,13-01-2016,1269051,0,2007,1,USD,Online Mode
3,366002,1,01-01-2016,12-01-2016,266019,0,1106,7,CAD,Online Mode
4,366002,2,01-01-2016,12-01-2016,266019,0,373,1,CAD,Online Mode

In [21]:
sales['OrderNumber'].nunique()

26326

In [116]:
#### Check the details informations
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  object
 3   Delivery Date  13165 non-null  object
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: int64(6), object(3)
memory usage: 4.3+ MB

In [117]:
sales.shape

(62884, 9)

In [118]:
sales.isnull().sum()

Order Number         0
Line Item            0
Order Date           0
Delivery Date    49719
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency Code        0
dtype: int64

In [119]:
sales.dtypes

Order Number      int64
Line Item         int64
Order Date       object
Delivery Date    object
CustomerKey       int64
StoreKey          int64
ProductKey        int64
Quantity          int64
Currency Code    object
dtype: object

#### 🛠️ Fix the date columns data types :-

#### Order Date :-

In [120]:
sales['Order Date'].unique()

array(['1/1/2016', '1/2/2016', '1/3/2016', ..., '2/18/2021', '2/19/2021',
       '2/20/2021'], dtype=object)

In [121]:
sales['Order Date'] = pd.to_datetime(sales['Order Date'])

In [122]:
sales.dtypes

Order Number              int64
Line Item                 int64
Order Date       datetime64[ns]
Delivery Date            object
CustomerKey               int64
StoreKey                  int64
ProductKey                int64
Quantity                  int64
Currency Code            object
dtype: object

#### Delivery Date :-

In [123]:
sales['Delivery Date'] = pd.to_datetime(sales['Delivery Date'])

In [124]:
sales.dtypes

Order Number              int64
Line Item                 int64
Order Date       datetime64[ns]
Delivery Date    datetime64[ns]
CustomerKey               int64
StoreKey                  int64
ProductKey                int64
Quantity                  int64
Currency Code            object
dtype: object

In [125]:
sales.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD

In [126]:

sales['Store Mode'] = np.where(
    sales['Delivery Date'].isna(),
    'Offline Store',
    'Online Mode'
)

In [127]:
sales.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,Store Mode
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD,Offline Store
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD,Online Mode
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD,Online Mode
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD,Online Mode
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD,Online Mode

In [128]:
sales.columns

Index(['Order Number', 'Line Item', 'Order Date', 'Delivery Date',
       'CustomerKey', 'StoreKey', 'ProductKey', 'Quantity', 'Currency Code',
       'Store Mode'],
      dtype='object')

In [129]:
sales.dtypes

Order Number              int64
Line Item                 int64
Order Date       datetime64[ns]
Delivery Date    datetime64[ns]
CustomerKey               int64
StoreKey                  int64
ProductKey                int64
Quantity                  int64
Currency Code            object
Store Mode               object
dtype: object

In [130]:
sales.to_csv(r'C:\Users\Rohit kumar\Downloads\sales.csv')

### 3). EDA on product Table:-

In [131]:
product.head()

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [132]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   object
 5   Unit Price USD  2517 non-null   object
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: int64(3), object(7)
memory usage: 196.8+ KB

In [133]:
product.shape

(2517, 10)

In [134]:
product.isnull().sum()

ProductKey        0
Product Name      0
Brand             0
Color             0
Unit Cost USD     0
Unit Price USD    0
SubcategoryKey    0
Subcategory       0
CategoryKey       0
Category          0
dtype: int64

In [135]:
product.dtypes

ProductKey         int64
Product Name      object
Brand             object
Color             object
Unit Cost USD     object
Unit Price USD    object
SubcategoryKey     int64
Subcategory       object
CategoryKey        int64
Category          object
dtype: object

#### Fix the data types Unit Cost USD & Unit Price USD :-

#### 1). Unit Cost USD  :-

In [136]:
### Check the column :-
product['Unit Cost USD'].head().unique()

array(['$6.62 ', '$7.40 ', '$11.00 '], dtype=object)

#### 🧹 Remove the dolllars sign from the columns :-

In [137]:
product['Unit Cost USD'] = product['Unit Cost USD'].str.replace('$',"")

#### 💡 Change the data types :-

In [138]:
product['Unit Cost USD'] = product['Unit Cost USD'].str.replace(',','').str.strip().astype(float)

In [139]:
product['Unit Cost USD'].head().unique()

array([ 6.62,  7.4 , 11.  ])

#### 2). Unit Price  USD  :-

#### 🧹 Remove the dolllars sign from the columns :-

In [140]:
product['Unit Price USD'] = product['Unit Price USD'].str.replace('$',"")

#### 💡 Change the data types :-

In [141]:
product['Unit Price USD'] = product['Unit Price USD'].str.replace(',','').str.strip().astype(float)

In [142]:
product.sample(5)

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
760,761,Contoso USB Data Link-direct connect adapter E...,Contoso,Black,8.62,16.90,308,Computers Accessories,3,Computers
373,374,Adventure Works Laptop19W X1980 Silver,Adventure Works,Silver,430.38,1299.00,301,Laptops,3,Computers
2082,2083,Contoso Microwave 0.9CuFt E0090 Black,Contoso,Black,50.98,99.99,803,Microwaves,8,Home Appliances
1666,1667,MGS Hand Games for kids E300 Black,Tailspin Toys,Black,2.80,5.50,701,Boxed Games,7,Games and Toys
118,119,"Adventure Works 13"" Color TV E25 Silver",Adventure Works,Silver,61.17,119.99,201,Televisions,2,TV and Video

In [143]:
product.dtypes

ProductKey          int64
Product Name       object
Brand              object
Color              object
Unit Cost USD     float64
Unit Price USD    float64
SubcategoryKey      int64
Subcategory        object
CategoryKey         int64
Category           object
dtype: object

In [144]:
### Check the ',' in cost and price usd columns:-
product[product['ProductKey'] == 1882]

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
1881,1882,Contoso Washer & Dryer 27in L270 Green,Contoso,Green,878.66,2652.0,801,Washers & Dryers,8,Home Appliances

In [48]:
# 1882 ProductKey

In [145]:
product.to_csv(r'C:\Users\Rohit kumar\Downloads\product.csv')

#### Check the product name :-

In [51]:
product['Product Name'].nunique()

2517

In [53]:
product['Brand'].unique()

array(['Contoso', 'Wide World Importers', 'Northwind Traders',
       'Adventure Works', 'Southridge Video', 'Litware', 'Fabrikam',
       'Proseware', 'A. Datum', 'The Phone Company', 'Tailspin Toys'],
      dtype=object)

In [58]:
product.groupby('Brand')['Product Name'].unique()

Brand
A. Datum                [A. Datum Compact Digital Camera M200 Black, A...
Adventure Works         [Adventure Works 20" CRT TV E15 Silver, Advent...
Contoso                 [Contoso 512MB MP3 Player E51 Silver, Contoso ...
Fabrikam                [Fabrikam Laptop19W M9800 Black, Fabrikam Lapt...
Litware                 [Litware Home Theater System 4.1 Channel M410 ...
Northwind Traders       [NT Bluetooth Stereo Headphones E52 Blue, NT B...
Proseware               [Proseware Laptop19 X910 Black, Proseware Lapt...
Southridge Video        [SV 16xDVD M300 Black, SV 8xDVD E100 Black, SV...
Tailspin Toys           [MGS Hand Games for kids E300 Yellow, MGS Hand...
The Phone Company       [The Phone Company Touch Screen Phone 1600 TFT...
Wide World Importers    [WWI 1GB Pulse Smart pen E50 White, WWI 1GBPul...
Name: Product Name, dtype: object

In [59]:
product.groupby('Product Name')['Subcategory'].unique()

Product Name
A. Datum Advanced Digital Camera M300 Azure                           [Digital Cameras]
A. Datum Advanced Digital Camera M300 Black                           [Digital Cameras]
A. Datum Advanced Digital Camera M300 Green                           [Digital Cameras]
A. Datum Advanced Digital Camera M300 Grey                            [Digital Cameras]
A. Datum Advanced Digital Camera M300 Orange                          [Digital Cameras]
                                                                          ...
WWI Wireless Transmitter and Bluetooth Headphones X250 Black     [Bluetooth Headphones]
WWI Wireless Transmitter and Bluetooth Headphones X250 Blue      [Bluetooth Headphones]
WWI Wireless Transmitter and Bluetooth Headphones X250 Red       [Bluetooth Headphones]
WWI Wireless Transmitter and Bluetooth Headphones X250 Silver    [Bluetooth Headphones]
WWI Wireless Transmitter and Bluetooth Headphones X250 White     [Bluetooth Headphones]
Name: Subcategory, Length: 2517, dtype: object

In [3]:
product.groupby('Category')['Subcategory'].unique()

Category
Audio                               [MP4&MP3, Recording Pen, Bluetooth Headphones]
Cameras and camcorders           [Digital Cameras, Digital SLR Cameras, Camcord...
Cell phones                      [Home & Office Phones, Touch Screen Phones, Sm...
Computers                        [Laptops, Desktops, Monitors, Projectors & Scr...
Games and Toys                                       [Boxed Games, Download Games]
Home Appliances                  [Washers & Dryers, Refrigerators, Microwaves, ...
Music, Movies and Audio Books                                          [Movie DVD]
TV and Video                     [Televisions, VCD & DVD, Home Theater System, ...
Name: Subcategory, dtype: object

### 4). EDA on Exchange Table:-

In [146]:
Exchange.head()

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415

In [147]:
Exchange.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11215 entries, 0 to 11214
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      11215 non-null  object
 1   Currency  11215 non-null  object
 2   Exchange  11215 non-null  float64
dtypes: float64(1), object(2)
memory usage: 263.0+ KB

#### ✔️ Check the data types of columns :-

In [148]:

Exchange.dtypes

Date         object
Currency     object
Exchange    float64
dtype: object

#### 🛠️ Fix the data types of Date columns :-

In [149]:
Exchange['Date'] = pd.to_datetime(Exchange['Date'])

In [150]:
Exchange.dtypes

Date        datetime64[ns]
Currency            object
Exchange           float64
dtype: object

In [151]:
Exchange.head()

        Date Currency  Exchange
0 2015-01-01      USD    1.0000
1 2015-01-01      CAD    1.1583
2 2015-01-01      AUD    1.2214
3 2015-01-01      EUR    0.8237
4 2015-01-01      GBP    0.6415

In [152]:
Exchange.to_csv(r'C:\Users\Rohit kumar\Downloads\Exchange.csv')

### 5). EDA on Store Table:-

In [17]:
Stores.head()

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

StoreKey           int64
Country           object
State             object
Square Meters    float64
Open Date         object
dtype: object

#### ✔️ Check the data types of columns :-

In [20]:
Stores.dtypes

StoreKey           int64
Country           object
State             object
Square Meters    float64
Open Date         object
dtype: object

#### 🛠️ Fix the data types of Date columns :-

In [31]:
Stores['Open Date'] = pd.to_datetime(Stores['Open Date'])

In [32]:
Stores.dtypes

StoreKey                  int64
Country                  object
State                    object
Square Meters           float64
Open Date        datetime64[ns]
dtype: object

In [33]:
Stores.head()

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0 2008-01-01
1         2  Australia            Northern Territory          665.0 2008-01-12
2         3  Australia               South Australia         2000.0 2012-01-07
3         4  Australia                      Tasmania         2000.0 2010-01-01
4         5  Australia                      Victoria         2000.0 2015-12-09

In [34]:
Stores.shape

(67, 5)

### Now save csv file :-

In [41]:
Stores.to_csv(r'C:\Users\Rohit kumar\Downloads\store.csv')

AttributeError: 'NoneType' object has no attribute 'to_csv'

In [43]:
product.to_csv(r'C:\Users\Rohit kumar\Downloads\Product.csv')

In [48]:
product.head()

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [44]:
Exchange.to_csv(r'C:\Users\Rohit kumar\Downloads\Exchange.csv')

In [45]:
sales.to_csv(r'C:\Users\Rohit kumar\Downloads\sales.csv')

NameError: name 'sales' is not defined

In [47]:
cust.to_csv(r'C:\Users\Rohit kumar\Downloads\customer.csv')

NameError: name 'cust' is not defined